// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: albums.sql

package sqlc

import (
	"context"
	"time"
)

const countAlbumsByUser = `-- name: CountAlbumsByUser :one
SELECT COUNT(*) FROM albums
WHERE user_id = $1
AND ($2::text IS NULL OR name ILIKE '%' || $2 || '%')
`

type CountAlbumsByUserParams struct {
	UserID  int64  `json:"user_id"`
	Column2 string `json:"column_2"`
}

func (q *Queries) CountAlbumsByUser(ctx context.Context, arg CountAlbumsByUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAlbumsByUser, arg.UserID, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAlbum = `-- name: CreateAlbum :one
INSERT INTO albums (user_id, name, intro)
VALUES ($1, $2, $3)
RETURNING id, user_id, name, intro, image_num, created_at, updated_at
`

type CreateAlbumParams struct {
	UserID int64  `json:"user_id"`
	Name   string `json:"name"`
	Intro  string `json:"intro"`
}

func (q *Queries) CreateAlbum(ctx context.Context, arg CreateAlbumParams) (Album, error) {
	row := q.db.QueryRow(ctx, createAlbum, arg.UserID, arg.Name, arg.Intro)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Intro,
		&i.ImageNum,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const decrementAlbumImageNum = `-- name: DecrementAlbumImageNum :exec
UPDATE albums SET image_num = image_num - 1, updated_at = NOW() WHERE id = $1 AND image_num > 0
`

func (q *Queries) DecrementAlbumImageNum(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, decrementAlbumImageNum, id)
	return err
}

const decrementUserAlbumNum = `-- name: DecrementUserAlbumNum :exec
UPDATE users SET album_num = album_num - 1, updated_at = NOW() WHERE id = $1 AND album_num > 0
`

func (q *Queries) DecrementUserAlbumNum(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, decrementUserAlbumNum, id)
	return err
}

const deleteAlbum = `-- name: DeleteAlbum :exec
DELETE FROM albums WHERE id = $1
`

func (q *Queries) DeleteAlbum(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteAlbum, id)
	return err
}

const getAlbumByID = `-- name: GetAlbumByID :one
SELECT id, user_id, name, intro, image_num, created_at, updated_at FROM albums WHERE id = $1
`

func (q *Queries) GetAlbumByID(ctx context.Context, id int64) (Album, error) {
	row := q.db.QueryRow(ctx, getAlbumByID, id)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Intro,
		&i.ImageNum,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementAlbumImageNum = `-- name: IncrementAlbumImageNum :exec
UPDATE albums SET image_num = image_num + 1, updated_at = NOW() WHERE id = $1
`

func (q *Queries) IncrementAlbumImageNum(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, incrementAlbumImageNum, id)
	return err
}

const incrementUserAlbumNum = `-- name: IncrementUserAlbumNum :exec
UPDATE users SET album_num = album_num + 1, updated_at = NOW() WHERE id = $1
`

func (q *Queries) IncrementUserAlbumNum(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, incrementUserAlbumNum, id)
	return err
}

const listAlbumsByUser = `-- name: ListAlbumsByUser :many
SELECT a.id, a.user_id, a.name, a.intro, a.image_num, a.created_at, a.updated_at,
    COALESCE((SELECT md5 FROM images i WHERE i.album_id = a.id ORDER BY i.created_at DESC LIMIT 1), '') as cover_md5
FROM albums a
WHERE a.user_id = $1
AND ($2::text IS NULL OR a.name ILIKE '%' || $2 || '%')
ORDER BY
    CASE WHEN $3 = 'newest' THEN a.created_at END DESC,
    CASE WHEN $3 = 'earliest' THEN a.created_at END ASC,
    CASE WHEN $3 = 'most' THEN a.image_num END DESC,
    CASE WHEN $3 = 'least' THEN a.image_num END ASC,
    a.created_at DESC
LIMIT $4 OFFSET $5
`

type ListAlbumsByUserParams struct {
	UserID  int64       `json:"user_id"`
	Column2 string      `json:"column_2"`
	Column3 interface{} `json:"column_3"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

type ListAlbumsByUserRow struct {
	ID        int64       `json:"id"`
	UserID    int64       `json:"user_id"`
	Name      string      `json:"name"`
	Intro     string      `json:"intro"`
	ImageNum  int64       `json:"image_num"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
	CoverMd5  interface{} `json:"cover_md5"`
}

func (q *Queries) ListAlbumsByUser(ctx context.Context, arg ListAlbumsByUserParams) ([]ListAlbumsByUserRow, error) {
	rows, err := q.db.Query(ctx, listAlbumsByUser,
		arg.UserID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAlbumsByUserRow{}
	for rows.Next() {
		var i ListAlbumsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Intro,
			&i.ImageNum,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CoverMd5,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAlbum = `-- name: UpdateAlbum :one
UPDATE albums SET
    name = COALESCE($2, name),
    intro = COALESCE($3, intro),
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, name, intro, image_num, created_at, updated_at
`

type UpdateAlbumParams struct {
	ID    int64  `json:"id"`
	Name  string `json:"name"`
	Intro string `json:"intro"`
}

func (q *Queries) UpdateAlbum(ctx context.Context, arg UpdateAlbumParams) (Album, error) {
	row := q.db.QueryRow(ctx, updateAlbum, arg.ID, arg.Name, arg.Intro)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Intro,
		&i.ImageNum,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
