// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_logs.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAuditLogs = `-- name: CountAuditLogs :one
SELECT COUNT(*)
FROM audit_logs al
WHERE ($1::text IS NULL OR al.action = $1)
  AND ($2::text IS NULL OR al.resource_type = $2)
`

type CountAuditLogsParams struct {
	Action       pgtype.Text `json:"action"`
	ResourceType pgtype.Text `json:"resource_type"`
}

func (q *Queries) CountAuditLogs(ctx context.Context, arg CountAuditLogsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogs, arg.Action, arg.ResourceType)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuditLog = `-- name: CreateAuditLog :exec
INSERT INTO audit_logs (
    actor_user_id,
    action,
    resource_type,
    resource_id,
    resource_name,
    details,
    ip,
    user_agent
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateAuditLogParams struct {
	ActorUserID  pgtype.Int8     `json:"actor_user_id"`
	Action       string          `json:"action"`
	ResourceType string          `json:"resource_type"`
	ResourceID   pgtype.Text     `json:"resource_id"`
	ResourceName pgtype.Text     `json:"resource_name"`
	Details      json.RawMessage `json:"details"`
	Ip           string          `json:"ip"`
	UserAgent    string          `json:"user_agent"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error {
	_, err := q.db.Exec(ctx, createAuditLog,
		arg.ActorUserID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.ResourceName,
		arg.Details,
		arg.Ip,
		arg.UserAgent,
	)
	return err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT
    al.id, al.actor_user_id, al.action, al.resource_type, al.resource_id, al.resource_name, al.details, al.ip, al.user_agent, al.created_at,
    u.email AS actor_email
FROM audit_logs al
LEFT JOIN users u ON u.id = al.actor_user_id
WHERE ($3::text IS NULL OR al.action = $3)
  AND ($4::text IS NULL OR al.resource_type = $4)
ORDER BY al.created_at DESC
LIMIT $1 OFFSET $2
`

type ListAuditLogsParams struct {
	Limit        int32       `json:"limit"`
	Offset       int32       `json:"offset"`
	Action       pgtype.Text `json:"action"`
	ResourceType pgtype.Text `json:"resource_type"`
}

type ListAuditLogsRow struct {
	ID           int64           `json:"id"`
	ActorUserID  pgtype.Int8     `json:"actor_user_id"`
	Action       string          `json:"action"`
	ResourceType string          `json:"resource_type"`
	ResourceID   pgtype.Text     `json:"resource_id"`
	ResourceName pgtype.Text     `json:"resource_name"`
	Details      json.RawMessage `json:"details"`
	Ip           string          `json:"ip"`
	UserAgent    string          `json:"user_agent"`
	CreatedAt    time.Time       `json:"created_at"`
	ActorEmail   pgtype.Text     `json:"actor_email"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]ListAuditLogsRow, error) {
	rows, err := q.db.Query(ctx, listAuditLogs,
		arg.Limit,
		arg.Offset,
		arg.Action,
		arg.ResourceType,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditLogsRow{}
	for rows.Next() {
		var i ListAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.ActorUserID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.ResourceName,
			&i.Details,
			&i.Ip,
			&i.UserAgent,
			&i.CreatedAt,
			&i.ActorEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
