// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_verification_tokens.sql

package sqlc

import (
	"context"
	"time"
)

const createEmailVerificationToken = `-- name: CreateEmailVerificationToken :one
INSERT INTO email_verification_tokens (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, expires_at, used_at, created_at
`

type CreateEmailVerificationTokenParams struct {
	UserID    int64     `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateEmailVerificationToken(ctx context.Context, arg CreateEmailVerificationTokenParams) (EmailVerificationToken, error) {
	row := q.db.QueryRow(ctx, createEmailVerificationToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i EmailVerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEmailVerificationTokenByHash = `-- name: DeleteEmailVerificationTokenByHash :exec
DELETE FROM email_verification_tokens
WHERE token_hash = $1
`

func (q *Queries) DeleteEmailVerificationTokenByHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteEmailVerificationTokenByHash, tokenHash)
	return err
}

const deleteUnusedEmailVerificationTokensByUser = `-- name: DeleteUnusedEmailVerificationTokensByUser :exec
DELETE FROM email_verification_tokens
WHERE user_id = $1 AND used_at IS NULL
`

func (q *Queries) DeleteUnusedEmailVerificationTokensByUser(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteUnusedEmailVerificationTokensByUser, userID)
	return err
}

const getEmailVerificationTokenByHash = `-- name: GetEmailVerificationTokenByHash :one
SELECT id, user_id, token_hash, expires_at, used_at, created_at FROM email_verification_tokens WHERE token_hash = $1
`

func (q *Queries) GetEmailVerificationTokenByHash(ctx context.Context, tokenHash string) (EmailVerificationToken, error) {
	row := q.db.QueryRow(ctx, getEmailVerificationTokenByHash, tokenHash)
	var i EmailVerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestUnusedEmailVerificationTokenByUser = `-- name: GetLatestUnusedEmailVerificationTokenByUser :one
SELECT id, user_id, token_hash, expires_at, used_at, created_at
FROM email_verification_tokens
WHERE user_id = $1 AND used_at IS NULL
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestUnusedEmailVerificationTokenByUser(ctx context.Context, userID int64) (EmailVerificationToken, error) {
	row := q.db.QueryRow(ctx, getLatestUnusedEmailVerificationTokenByUser, userID)
	var i EmailVerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markEmailVerificationTokenUsed = `-- name: MarkEmailVerificationTokenUsed :one
UPDATE email_verification_tokens
SET used_at = NOW()
WHERE id = $1 AND used_at IS NULL
RETURNING id, user_id, token_hash, expires_at, used_at, created_at
`

func (q *Queries) MarkEmailVerificationTokenUsed(ctx context.Context, id int64) (EmailVerificationToken, error) {
	row := q.db.QueryRow(ctx, markEmailVerificationTokenUsed, id)
	var i EmailVerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}
