// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: groups.sql

package sqlc

import (
	"context"
	"encoding/json"
)

const addGroupStrategy = `-- name: AddGroupStrategy :exec
INSERT INTO group_strategies (group_id, strategy_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddGroupStrategyParams struct {
	GroupID    int64 `json:"group_id"`
	StrategyID int64 `json:"strategy_id"`
}

func (q *Queries) AddGroupStrategy(ctx context.Context, arg AddGroupStrategyParams) error {
	_, err := q.db.Exec(ctx, addGroupStrategy, arg.GroupID, arg.StrategyID)
	return err
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (name, is_default, is_guest, configs)
VALUES ($1, $2, $3, $4)
RETURNING id, name, is_default, is_guest, configs, created_at, updated_at
`

type CreateGroupParams struct {
	Name      string          `json:"name"`
	IsDefault bool            `json:"is_default"`
	IsGuest   bool            `json:"is_guest"`
	Configs   json.RawMessage `json:"configs"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, createGroup,
		arg.Name,
		arg.IsDefault,
		arg.IsGuest,
		arg.Configs,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsDefault,
		&i.IsGuest,
		&i.Configs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGroup = `-- name: DeleteGroup :exec
DELETE FROM groups WHERE id = $1
`

func (q *Queries) DeleteGroup(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteGroup, id)
	return err
}

const getDefaultGroup = `-- name: GetDefaultGroup :one
SELECT id, name, is_default, is_guest, configs, created_at, updated_at FROM groups WHERE is_default = TRUE LIMIT 1
`

func (q *Queries) GetDefaultGroup(ctx context.Context) (Group, error) {
	row := q.db.QueryRow(ctx, getDefaultGroup)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsDefault,
		&i.IsGuest,
		&i.Configs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGroupByID = `-- name: GetGroupByID :one
SELECT id, name, is_default, is_guest, configs, created_at, updated_at FROM groups WHERE id = $1
`

func (q *Queries) GetGroupByID(ctx context.Context, id int64) (Group, error) {
	row := q.db.QueryRow(ctx, getGroupByID, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsDefault,
		&i.IsGuest,
		&i.Configs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGroupStrategies = `-- name: GetGroupStrategies :many
SELECT s.id, s.name, s.strategy_type, s.configs, s.created_at, s.updated_at FROM strategies s
JOIN group_strategies gs ON s.id = gs.strategy_id
WHERE gs.group_id = $1
`

func (q *Queries) GetGroupStrategies(ctx context.Context, groupID int64) ([]Strategy, error) {
	rows, err := q.db.Query(ctx, getGroupStrategies, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Strategy{}
	for rows.Next() {
		var i Strategy
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.StrategyType,
			&i.Configs,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGuestGroup = `-- name: GetGuestGroup :one
SELECT id, name, is_default, is_guest, configs, created_at, updated_at FROM groups WHERE is_guest = TRUE LIMIT 1
`

func (q *Queries) GetGuestGroup(ctx context.Context) (Group, error) {
	row := q.db.QueryRow(ctx, getGuestGroup)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsDefault,
		&i.IsGuest,
		&i.Configs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGroups = `-- name: ListGroups :many
SELECT id, name, is_default, is_guest, configs, created_at, updated_at FROM groups ORDER BY created_at DESC
`

func (q *Queries) ListGroups(ctx context.Context) ([]Group, error) {
	rows, err := q.db.Query(ctx, listGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Group{}
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsDefault,
			&i.IsGuest,
			&i.Configs,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeGroupStrategy = `-- name: RemoveGroupStrategy :exec
DELETE FROM group_strategies WHERE group_id = $1 AND strategy_id = $2
`

type RemoveGroupStrategyParams struct {
	GroupID    int64 `json:"group_id"`
	StrategyID int64 `json:"strategy_id"`
}

func (q *Queries) RemoveGroupStrategy(ctx context.Context, arg RemoveGroupStrategyParams) error {
	_, err := q.db.Exec(ctx, removeGroupStrategy, arg.GroupID, arg.StrategyID)
	return err
}

const replaceGroupStrategies = `-- name: ReplaceGroupStrategies :exec
DELETE FROM group_strategies WHERE group_id = $1
`

func (q *Queries) ReplaceGroupStrategies(ctx context.Context, groupID int64) error {
	_, err := q.db.Exec(ctx, replaceGroupStrategies, groupID)
	return err
}

const unsetOtherDefault = `-- name: UnsetOtherDefault :exec
UPDATE groups SET is_default = FALSE, updated_at = NOW() WHERE id != $1 AND is_default = TRUE
`

func (q *Queries) UnsetOtherDefault(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, unsetOtherDefault, id)
	return err
}

const unsetOtherGuest = `-- name: UnsetOtherGuest :exec
UPDATE groups SET is_guest = FALSE, updated_at = NOW() WHERE id != $1 AND is_guest = TRUE
`

func (q *Queries) UnsetOtherGuest(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, unsetOtherGuest, id)
	return err
}

const updateGroup = `-- name: UpdateGroup :one
UPDATE groups SET
    name = $2,
    is_default = $3,
    is_guest = $4,
    configs = $5,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, is_default, is_guest, configs, created_at, updated_at
`

type UpdateGroupParams struct {
	ID        int64           `json:"id"`
	Name      string          `json:"name"`
	IsDefault bool            `json:"is_default"`
	IsGuest   bool            `json:"is_guest"`
	Configs   json.RawMessage `json:"configs"`
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, updateGroup,
		arg.ID,
		arg.Name,
		arg.IsDefault,
		arg.IsGuest,
		arg.Configs,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsDefault,
		&i.IsGuest,
		&i.Configs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
