// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: images.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAllImages = `-- name: CountAllImages :one
SELECT COUNT(*) FROM images
`

func (q *Queries) CountAllImages(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllImages)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countImagesByUser = `-- name: CountImagesByUser :one
SELECT COUNT(*) FROM images WHERE user_id = $1
`

func (q *Queries) CountImagesByUser(ctx context.Context, userID pgtype.Int8) (int64, error) {
	row := q.db.QueryRow(ctx, countImagesByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countImagesInWindow = `-- name: CountImagesInWindow :one
SELECT COUNT(*) FROM images
WHERE user_id = $1
AND created_at > NOW() - ($2::text || ' seconds')::interval
`

type CountImagesInWindowParams struct {
	UserID  pgtype.Int8 `json:"user_id"`
	Column2 string      `json:"column_2"`
}

func (q *Queries) CountImagesInWindow(ctx context.Context, arg CountImagesInWindowParams) (int64, error) {
	row := q.db.QueryRow(ctx, countImagesInWindow, arg.UserID, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countImagesInWindowByIP = `-- name: CountImagesInWindowByIP :one
SELECT COUNT(*) FROM images
WHERE user_id IS NULL AND uploaded_ip = $1
AND created_at > NOW() - ($2::text || ' seconds')::interval
`

type CountImagesInWindowByIPParams struct {
	UploadedIp string `json:"uploaded_ip"`
	Column2    string `json:"column_2"`
}

func (q *Queries) CountImagesInWindowByIP(ctx context.Context, arg CountImagesInWindowByIPParams) (int64, error) {
	row := q.db.QueryRow(ctx, countImagesInWindowByIP, arg.UploadedIp, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createImage = `-- name: CreateImage :one
INSERT INTO images (user_id, album_id, group_id, strategy_id, key, path, name, origin_name, size_bytes, mimetype, extension, md5, sha1, width, height, permission, uploaded_ip, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
RETURNING id, user_id, album_id, group_id, strategy_id, key, path, name, origin_name, size_bytes, mimetype, extension, md5, sha1, width, height, permission, is_unhealthy, uploaded_ip, created_at, updated_at, moderation_status, expires_at
`

type CreateImageParams struct {
	UserID     pgtype.Int8        `json:"user_id"`
	AlbumID    pgtype.Int8        `json:"album_id"`
	GroupID    pgtype.Int8        `json:"group_id"`
	StrategyID pgtype.Int8        `json:"strategy_id"`
	Key        string             `json:"key"`
	Path       string             `json:"path"`
	Name       string             `json:"name"`
	OriginName string             `json:"origin_name"`
	SizeBytes  int64              `json:"size_bytes"`
	Mimetype   string             `json:"mimetype"`
	Extension  string             `json:"extension"`
	Md5        string             `json:"md5"`
	Sha1       string             `json:"sha1"`
	Width      int32              `json:"width"`
	Height     int32              `json:"height"`
	Permission int16              `json:"permission"`
	UploadedIp string             `json:"uploaded_ip"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateImage(ctx context.Context, arg CreateImageParams) (Image, error) {
	row := q.db.QueryRow(ctx, createImage,
		arg.UserID,
		arg.AlbumID,
		arg.GroupID,
		arg.StrategyID,
		arg.Key,
		arg.Path,
		arg.Name,
		arg.OriginName,
		arg.SizeBytes,
		arg.Mimetype,
		arg.Extension,
		arg.Md5,
		arg.Sha1,
		arg.Width,
		arg.Height,
		arg.Permission,
		arg.UploadedIp,
		arg.ExpiresAt,
	)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AlbumID,
		&i.GroupID,
		&i.StrategyID,
		&i.Key,
		&i.Path,
		&i.Name,
		&i.OriginName,
		&i.SizeBytes,
		&i.Mimetype,
		&i.Extension,
		&i.Md5,
		&i.Sha1,
		&i.Width,
		&i.Height,
		&i.Permission,
		&i.IsUnhealthy,
		&i.UploadedIp,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ModerationStatus,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteImage = `-- name: DeleteImage :exec
DELETE FROM images WHERE id = $1
`

func (q *Queries) DeleteImage(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteImage, id)
	return err
}

const deleteImageByKey = `-- name: DeleteImageByKey :exec
DELETE FROM images WHERE key = $1
`

func (q *Queries) DeleteImageByKey(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, deleteImageByKey, key)
	return err
}

const findDuplicateImage = `-- name: FindDuplicateImage :one
SELECT id, user_id, album_id, group_id, strategy_id, key, path, name, origin_name, size_bytes, mimetype, extension, md5, sha1, width, height, permission, is_unhealthy, uploaded_ip, created_at, updated_at, moderation_status, expires_at FROM images
WHERE strategy_id = $1 AND md5 = $2 AND sha1 = $3
LIMIT 1
`

type FindDuplicateImageParams struct {
	StrategyID pgtype.Int8 `json:"strategy_id"`
	Md5        string      `json:"md5"`
	Sha1       string      `json:"sha1"`
}

func (q *Queries) FindDuplicateImage(ctx context.Context, arg FindDuplicateImageParams) (Image, error) {
	row := q.db.QueryRow(ctx, findDuplicateImage, arg.StrategyID, arg.Md5, arg.Sha1)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AlbumID,
		&i.GroupID,
		&i.StrategyID,
		&i.Key,
		&i.Path,
		&i.Name,
		&i.OriginName,
		&i.SizeBytes,
		&i.Mimetype,
		&i.Extension,
		&i.Md5,
		&i.Sha1,
		&i.Width,
		&i.Height,
		&i.Permission,
		&i.IsUnhealthy,
		&i.UploadedIp,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ModerationStatus,
		&i.ExpiresAt,
	)
	return i, err
}

const getExpiredImages = `-- name: GetExpiredImages :many
SELECT id, user_id, album_id, group_id, strategy_id, key, path, name, origin_name, size_bytes, mimetype, extension, md5, sha1, width, height, permission, is_unhealthy, uploaded_ip, created_at, updated_at, moderation_status, expires_at FROM images
WHERE expires_at IS NOT NULL AND expires_at <= NOW()
ORDER BY expires_at ASC
LIMIT $1
`

func (q *Queries) GetExpiredImages(ctx context.Context, limit int32) ([]Image, error) {
	rows, err := q.db.Query(ctx, getExpiredImages, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Image{}
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AlbumID,
			&i.GroupID,
			&i.StrategyID,
			&i.Key,
			&i.Path,
			&i.Name,
			&i.OriginName,
			&i.SizeBytes,
			&i.Mimetype,
			&i.Extension,
			&i.Md5,
			&i.Sha1,
			&i.Width,
			&i.Height,
			&i.Permission,
			&i.IsUnhealthy,
			&i.UploadedIp,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ModerationStatus,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getImageByID = `-- name: GetImageByID :one
SELECT id, user_id, album_id, group_id, strategy_id, key, path, name, origin_name, size_bytes, mimetype, extension, md5, sha1, width, height, permission, is_unhealthy, uploaded_ip, created_at, updated_at, moderation_status, expires_at FROM images WHERE id = $1
`

func (q *Queries) GetImageByID(ctx context.Context, id int64) (Image, error) {
	row := q.db.QueryRow(ctx, getImageByID, id)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AlbumID,
		&i.GroupID,
		&i.StrategyID,
		&i.Key,
		&i.Path,
		&i.Name,
		&i.OriginName,
		&i.SizeBytes,
		&i.Mimetype,
		&i.Extension,
		&i.Md5,
		&i.Sha1,
		&i.Width,
		&i.Height,
		&i.Permission,
		&i.IsUnhealthy,
		&i.UploadedIp,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ModerationStatus,
		&i.ExpiresAt,
	)
	return i, err
}

const getImageByKey = `-- name: GetImageByKey :one
SELECT id, user_id, album_id, group_id, strategy_id, key, path, name, origin_name, size_bytes, mimetype, extension, md5, sha1, width, height, permission, is_unhealthy, uploaded_ip, created_at, updated_at, moderation_status, expires_at FROM images WHERE key = $1
`

func (q *Queries) GetImageByKey(ctx context.Context, key string) (Image, error) {
	row := q.db.QueryRow(ctx, getImageByKey, key)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AlbumID,
		&i.GroupID,
		&i.StrategyID,
		&i.Key,
		&i.Path,
		&i.Name,
		&i.OriginName,
		&i.SizeBytes,
		&i.Mimetype,
		&i.Extension,
		&i.Md5,
		&i.Sha1,
		&i.Width,
		&i.Height,
		&i.Permission,
		&i.IsUnhealthy,
		&i.UploadedIp,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ModerationStatus,
		&i.ExpiresAt,
	)
	return i, err
}

const listAllImages = `-- name: ListAllImages :many
SELECT images.id, images.user_id, images.album_id, images.group_id, images.strategy_id, images.key, images.path, images.name, images.origin_name, images.size_bytes, images.mimetype, images.extension, images.md5, images.sha1, images.width, images.height, images.permission, images.is_unhealthy, images.uploaded_ip, images.created_at, images.updated_at, images.moderation_status, images.expires_at, users.email as user_email FROM images
LEFT JOIN users ON images.user_id = users.id
ORDER BY images.created_at DESC
LIMIT $1 OFFSET $2
`

type ListAllImagesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListAllImagesRow struct {
	ID               int64              `json:"id"`
	UserID           pgtype.Int8        `json:"user_id"`
	AlbumID          pgtype.Int8        `json:"album_id"`
	GroupID          pgtype.Int8        `json:"group_id"`
	StrategyID       pgtype.Int8        `json:"strategy_id"`
	Key              string             `json:"key"`
	Path             string             `json:"path"`
	Name             string             `json:"name"`
	OriginName       string             `json:"origin_name"`
	SizeBytes        int64              `json:"size_bytes"`
	Mimetype         string             `json:"mimetype"`
	Extension        string             `json:"extension"`
	Md5              string             `json:"md5"`
	Sha1             string             `json:"sha1"`
	Width            int32              `json:"width"`
	Height           int32              `json:"height"`
	Permission       int16              `json:"permission"`
	IsUnhealthy      bool               `json:"is_unhealthy"`
	UploadedIp       string             `json:"uploaded_ip"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
	ModerationStatus string             `json:"moderation_status"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	UserEmail        pgtype.Text        `json:"user_email"`
}

func (q *Queries) ListAllImages(ctx context.Context, arg ListAllImagesParams) ([]ListAllImagesRow, error) {
	rows, err := q.db.Query(ctx, listAllImages, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllImagesRow{}
	for rows.Next() {
		var i ListAllImagesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AlbumID,
			&i.GroupID,
			&i.StrategyID,
			&i.Key,
			&i.Path,
			&i.Name,
			&i.OriginName,
			&i.SizeBytes,
			&i.Mimetype,
			&i.Extension,
			&i.Md5,
			&i.Sha1,
			&i.Width,
			&i.Height,
			&i.Permission,
			&i.IsUnhealthy,
			&i.UploadedIp,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ModerationStatus,
			&i.ExpiresAt,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImagesByUser = `-- name: ListImagesByUser :many
SELECT
    images.id, images.user_id, images.album_id, images.group_id, images.strategy_id, images.key, images.path, images.name, images.origin_name, images.size_bytes, images.mimetype, images.extension, images.md5, images.sha1, images.width, images.height, images.permission, images.is_unhealthy, images.uploaded_ip, images.created_at, images.updated_at, images.moderation_status, images.expires_at,
    strategies.name as strategy_name,
    strategies.strategy_type as strategy_type
FROM images
LEFT JOIN strategies ON images.strategy_id = strategies.id
WHERE images.user_id = $1
ORDER BY images.created_at DESC
LIMIT $2 OFFSET $3
`

type ListImagesByUserParams struct {
	UserID pgtype.Int8 `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

type ListImagesByUserRow struct {
	ID               int64              `json:"id"`
	UserID           pgtype.Int8        `json:"user_id"`
	AlbumID          pgtype.Int8        `json:"album_id"`
	GroupID          pgtype.Int8        `json:"group_id"`
	StrategyID       pgtype.Int8        `json:"strategy_id"`
	Key              string             `json:"key"`
	Path             string             `json:"path"`
	Name             string             `json:"name"`
	OriginName       string             `json:"origin_name"`
	SizeBytes        int64              `json:"size_bytes"`
	Mimetype         string             `json:"mimetype"`
	Extension        string             `json:"extension"`
	Md5              string             `json:"md5"`
	Sha1             string             `json:"sha1"`
	Width            int32              `json:"width"`
	Height           int32              `json:"height"`
	Permission       int16              `json:"permission"`
	IsUnhealthy      bool               `json:"is_unhealthy"`
	UploadedIp       string             `json:"uploaded_ip"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
	ModerationStatus string             `json:"moderation_status"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	StrategyName     pgtype.Text        `json:"strategy_name"`
	StrategyType     pgtype.Text        `json:"strategy_type"`
}

func (q *Queries) ListImagesByUser(ctx context.Context, arg ListImagesByUserParams) ([]ListImagesByUserRow, error) {
	rows, err := q.db.Query(ctx, listImagesByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListImagesByUserRow{}
	for rows.Next() {
		var i ListImagesByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AlbumID,
			&i.GroupID,
			&i.StrategyID,
			&i.Key,
			&i.Path,
			&i.Name,
			&i.OriginName,
			&i.SizeBytes,
			&i.Mimetype,
			&i.Extension,
			&i.Md5,
			&i.Sha1,
			&i.Width,
			&i.Height,
			&i.Permission,
			&i.IsUnhealthy,
			&i.UploadedIp,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ModerationStatus,
			&i.ExpiresAt,
			&i.StrategyName,
			&i.StrategyType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateImage = `-- name: UpdateImage :one
UPDATE images SET
    album_id = COALESCE($2, album_id),
    permission = COALESCE($3, permission),
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, album_id, group_id, strategy_id, key, path, name, origin_name, size_bytes, mimetype, extension, md5, sha1, width, height, permission, is_unhealthy, uploaded_ip, created_at, updated_at, moderation_status, expires_at
`

type UpdateImageParams struct {
	ID         int64       `json:"id"`
	AlbumID    pgtype.Int8 `json:"album_id"`
	Permission int16       `json:"permission"`
}

func (q *Queries) UpdateImage(ctx context.Context, arg UpdateImageParams) (Image, error) {
	row := q.db.QueryRow(ctx, updateImage, arg.ID, arg.AlbumID, arg.Permission)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AlbumID,
		&i.GroupID,
		&i.StrategyID,
		&i.Key,
		&i.Path,
		&i.Name,
		&i.OriginName,
		&i.SizeBytes,
		&i.Mimetype,
		&i.Extension,
		&i.Md5,
		&i.Sha1,
		&i.Width,
		&i.Height,
		&i.Permission,
		&i.IsUnhealthy,
		&i.UploadedIp,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ModerationStatus,
		&i.ExpiresAt,
	)
	return i, err
}

const updateImageExpiration = `-- name: UpdateImageExpiration :exec
UPDATE images SET expires_at = $2, updated_at = NOW() WHERE id = $1
`

type UpdateImageExpirationParams struct {
	ID        int64              `json:"id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) UpdateImageExpiration(ctx context.Context, arg UpdateImageExpirationParams) error {
	_, err := q.db.Exec(ctx, updateImageExpiration, arg.ID, arg.ExpiresAt)
	return err
}
