// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: images.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAllImages = `-- name: CountAllImages :one
SELECT COUNT(*) FROM images i
LEFT JOIN users u ON i.user_id = u.id
WHERE ($1::text IS NULL OR i.origin_name ILIKE '%' || $1 || '%')
AND ($2::text IS NULL OR u.email ILIKE '%' || $2 || '%')
AND ($3::text IS NULL OR i.extension = $3)
AND ($4::smallint IS NULL OR i.permission = $4)
AND ($5::boolean IS NULL OR i.is_unhealthy = $5)
`

type CountAllImagesParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
	Column3 string `json:"column_3"`
	Column4 int16  `json:"column_4"`
	Column5 bool   `json:"column_5"`
}

func (q *Queries) CountAllImages(ctx context.Context, arg CountAllImagesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAllImages,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countImagesByUser = `-- name: CountImagesByUser :one
SELECT COUNT(*) FROM images
WHERE user_id = $1
AND ($2::bigint IS NULL OR album_id = $2)
AND ($3::smallint IS NULL OR permission = $3)
AND ($4::text IS NULL OR origin_name ILIKE '%' || $4 || '%')
`

type CountImagesByUserParams struct {
	UserID  pgtype.Int8 `json:"user_id"`
	Column2 int64       `json:"column_2"`
	Column3 int16       `json:"column_3"`
	Column4 string      `json:"column_4"`
}

func (q *Queries) CountImagesByUser(ctx context.Context, arg CountImagesByUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countImagesByUser,
		arg.UserID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countImagesInWindow = `-- name: CountImagesInWindow :one
SELECT COUNT(*) FROM images
WHERE ($1::bigint IS NULL OR user_id = $1)
AND ($2::text IS NULL OR uploaded_ip = $2)
AND created_at > NOW() - ($3::text || ' seconds')::interval
`

type CountImagesInWindowParams struct {
	Column1 int64  `json:"column_1"`
	Column2 string `json:"column_2"`
	Column3 string `json:"column_3"`
}

func (q *Queries) CountImagesInWindow(ctx context.Context, arg CountImagesInWindowParams) (int64, error) {
	row := q.db.QueryRow(ctx, countImagesInWindow, arg.Column1, arg.Column2, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createImage = `-- name: CreateImage :one
INSERT INTO images (user_id, album_id, group_id, strategy_id, key, path, name, origin_name, size_bytes, mimetype, extension, md5, sha1, width, height, permission, uploaded_ip)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17)
RETURNING id, user_id, album_id, group_id, strategy_id, key, path, name, origin_name, size_bytes, mimetype, extension, md5, sha1, width, height, permission, is_unhealthy, uploaded_ip, created_at, updated_at
`

type CreateImageParams struct {
	UserID     pgtype.Int8 `json:"user_id"`
	AlbumID    pgtype.Int8 `json:"album_id"`
	GroupID    pgtype.Int8 `json:"group_id"`
	StrategyID pgtype.Int8 `json:"strategy_id"`
	Key        string      `json:"key"`
	Path       string      `json:"path"`
	Name       string      `json:"name"`
	OriginName string      `json:"origin_name"`
	SizeBytes  int64       `json:"size_bytes"`
	Mimetype   string      `json:"mimetype"`
	Extension  string      `json:"extension"`
	Md5        string      `json:"md5"`
	Sha1       string      `json:"sha1"`
	Width      int32       `json:"width"`
	Height     int32       `json:"height"`
	Permission int16       `json:"permission"`
	UploadedIp string      `json:"uploaded_ip"`
}

func (q *Queries) CreateImage(ctx context.Context, arg CreateImageParams) (Image, error) {
	row := q.db.QueryRow(ctx, createImage,
		arg.UserID,
		arg.AlbumID,
		arg.GroupID,
		arg.StrategyID,
		arg.Key,
		arg.Path,
		arg.Name,
		arg.OriginName,
		arg.SizeBytes,
		arg.Mimetype,
		arg.Extension,
		arg.Md5,
		arg.Sha1,
		arg.Width,
		arg.Height,
		arg.Permission,
		arg.UploadedIp,
	)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AlbumID,
		&i.GroupID,
		&i.StrategyID,
		&i.Key,
		&i.Path,
		&i.Name,
		&i.OriginName,
		&i.SizeBytes,
		&i.Mimetype,
		&i.Extension,
		&i.Md5,
		&i.Sha1,
		&i.Width,
		&i.Height,
		&i.Permission,
		&i.IsUnhealthy,
		&i.UploadedIp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteImage = `-- name: DeleteImage :exec
DELETE FROM images WHERE id = $1
`

func (q *Queries) DeleteImage(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteImage, id)
	return err
}

const deleteImageByKey = `-- name: DeleteImageByKey :exec
DELETE FROM images WHERE key = $1
`

func (q *Queries) DeleteImageByKey(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, deleteImageByKey, key)
	return err
}

const findDuplicateImage = `-- name: FindDuplicateImage :one
SELECT id, user_id, album_id, group_id, strategy_id, key, path, name, origin_name, size_bytes, mimetype, extension, md5, sha1, width, height, permission, is_unhealthy, uploaded_ip, created_at, updated_at FROM images
WHERE strategy_id = $1 AND md5 = $2 AND sha1 = $3
LIMIT 1
`

type FindDuplicateImageParams struct {
	StrategyID pgtype.Int8 `json:"strategy_id"`
	Md5        string      `json:"md5"`
	Sha1       string      `json:"sha1"`
}

func (q *Queries) FindDuplicateImage(ctx context.Context, arg FindDuplicateImageParams) (Image, error) {
	row := q.db.QueryRow(ctx, findDuplicateImage, arg.StrategyID, arg.Md5, arg.Sha1)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AlbumID,
		&i.GroupID,
		&i.StrategyID,
		&i.Key,
		&i.Path,
		&i.Name,
		&i.OriginName,
		&i.SizeBytes,
		&i.Mimetype,
		&i.Extension,
		&i.Md5,
		&i.Sha1,
		&i.Width,
		&i.Height,
		&i.Permission,
		&i.IsUnhealthy,
		&i.UploadedIp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getImageByID = `-- name: GetImageByID :one
SELECT id, user_id, album_id, group_id, strategy_id, key, path, name, origin_name, size_bytes, mimetype, extension, md5, sha1, width, height, permission, is_unhealthy, uploaded_ip, created_at, updated_at FROM images WHERE id = $1
`

func (q *Queries) GetImageByID(ctx context.Context, id int64) (Image, error) {
	row := q.db.QueryRow(ctx, getImageByID, id)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AlbumID,
		&i.GroupID,
		&i.StrategyID,
		&i.Key,
		&i.Path,
		&i.Name,
		&i.OriginName,
		&i.SizeBytes,
		&i.Mimetype,
		&i.Extension,
		&i.Md5,
		&i.Sha1,
		&i.Width,
		&i.Height,
		&i.Permission,
		&i.IsUnhealthy,
		&i.UploadedIp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getImageByKey = `-- name: GetImageByKey :one
SELECT id, user_id, album_id, group_id, strategy_id, key, path, name, origin_name, size_bytes, mimetype, extension, md5, sha1, width, height, permission, is_unhealthy, uploaded_ip, created_at, updated_at FROM images WHERE key = $1
`

func (q *Queries) GetImageByKey(ctx context.Context, key string) (Image, error) {
	row := q.db.QueryRow(ctx, getImageByKey, key)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AlbumID,
		&i.GroupID,
		&i.StrategyID,
		&i.Key,
		&i.Path,
		&i.Name,
		&i.OriginName,
		&i.SizeBytes,
		&i.Mimetype,
		&i.Extension,
		&i.Md5,
		&i.Sha1,
		&i.Width,
		&i.Height,
		&i.Permission,
		&i.IsUnhealthy,
		&i.UploadedIp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllImages = `-- name: ListAllImages :many
SELECT i.id, i.user_id, i.album_id, i.group_id, i.strategy_id, i.key, i.path, i.name, i.origin_name, i.size_bytes, i.mimetype, i.extension, i.md5, i.sha1, i.width, i.height, i.permission, i.is_unhealthy, i.uploaded_ip, i.created_at, i.updated_at, u.email as user_email FROM images i
LEFT JOIN users u ON i.user_id = u.id
WHERE ($1::text IS NULL OR i.origin_name ILIKE '%' || $1 || '%')
AND ($2::text IS NULL OR u.email ILIKE '%' || $2 || '%')
AND ($3::text IS NULL OR i.extension = $3)
AND ($4::smallint IS NULL OR i.permission = $4)
AND ($5::boolean IS NULL OR i.is_unhealthy = $5)
ORDER BY i.created_at DESC
LIMIT $6 OFFSET $7
`

type ListAllImagesParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
	Column3 string `json:"column_3"`
	Column4 int16  `json:"column_4"`
	Column5 bool   `json:"column_5"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type ListAllImagesRow struct {
	ID          int64       `json:"id"`
	UserID      pgtype.Int8 `json:"user_id"`
	AlbumID     pgtype.Int8 `json:"album_id"`
	GroupID     pgtype.Int8 `json:"group_id"`
	StrategyID  pgtype.Int8 `json:"strategy_id"`
	Key         string      `json:"key"`
	Path        string      `json:"path"`
	Name        string      `json:"name"`
	OriginName  string      `json:"origin_name"`
	SizeBytes   int64       `json:"size_bytes"`
	Mimetype    string      `json:"mimetype"`
	Extension   string      `json:"extension"`
	Md5         string      `json:"md5"`
	Sha1        string      `json:"sha1"`
	Width       int32       `json:"width"`
	Height      int32       `json:"height"`
	Permission  int16       `json:"permission"`
	IsUnhealthy bool        `json:"is_unhealthy"`
	UploadedIp  string      `json:"uploaded_ip"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
	UserEmail   pgtype.Text `json:"user_email"`
}

func (q *Queries) ListAllImages(ctx context.Context, arg ListAllImagesParams) ([]ListAllImagesRow, error) {
	rows, err := q.db.Query(ctx, listAllImages,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllImagesRow{}
	for rows.Next() {
		var i ListAllImagesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AlbumID,
			&i.GroupID,
			&i.StrategyID,
			&i.Key,
			&i.Path,
			&i.Name,
			&i.OriginName,
			&i.SizeBytes,
			&i.Mimetype,
			&i.Extension,
			&i.Md5,
			&i.Sha1,
			&i.Width,
			&i.Height,
			&i.Permission,
			&i.IsUnhealthy,
			&i.UploadedIp,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImagesByUser = `-- name: ListImagesByUser :many
SELECT id, user_id, album_id, group_id, strategy_id, key, path, name, origin_name, size_bytes, mimetype, extension, md5, sha1, width, height, permission, is_unhealthy, uploaded_ip, created_at, updated_at FROM images
WHERE user_id = $1
AND ($2::bigint IS NULL OR album_id = $2)
AND ($3::smallint IS NULL OR permission = $3)
AND ($4::text IS NULL OR origin_name ILIKE '%' || $4 || '%')
ORDER BY created_at DESC
LIMIT $5 OFFSET $6
`

type ListImagesByUserParams struct {
	UserID  pgtype.Int8 `json:"user_id"`
	Column2 int64       `json:"column_2"`
	Column3 int16       `json:"column_3"`
	Column4 string      `json:"column_4"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) ListImagesByUser(ctx context.Context, arg ListImagesByUserParams) ([]Image, error) {
	rows, err := q.db.Query(ctx, listImagesByUser,
		arg.UserID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Image{}
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AlbumID,
			&i.GroupID,
			&i.StrategyID,
			&i.Key,
			&i.Path,
			&i.Name,
			&i.OriginName,
			&i.SizeBytes,
			&i.Mimetype,
			&i.Extension,
			&i.Md5,
			&i.Sha1,
			&i.Width,
			&i.Height,
			&i.Permission,
			&i.IsUnhealthy,
			&i.UploadedIp,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateImage = `-- name: UpdateImage :one
UPDATE images SET
    album_id = COALESCE($2, album_id),
    permission = COALESCE($3, permission),
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, album_id, group_id, strategy_id, key, path, name, origin_name, size_bytes, mimetype, extension, md5, sha1, width, height, permission, is_unhealthy, uploaded_ip, created_at, updated_at
`

type UpdateImageParams struct {
	ID         int64       `json:"id"`
	AlbumID    pgtype.Int8 `json:"album_id"`
	Permission int16       `json:"permission"`
}

func (q *Queries) UpdateImage(ctx context.Context, arg UpdateImageParams) (Image, error) {
	row := q.db.QueryRow(ctx, updateImage, arg.ID, arg.AlbumID, arg.Permission)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AlbumID,
		&i.GroupID,
		&i.StrategyID,
		&i.Key,
		&i.Path,
		&i.Name,
		&i.OriginName,
		&i.SizeBytes,
		&i.Mimetype,
		&i.Extension,
		&i.Md5,
		&i.Sha1,
		&i.Width,
		&i.Height,
		&i.Permission,
		&i.IsUnhealthy,
		&i.UploadedIp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
