// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: moderations.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approveAllPendingImages = `-- name: ApproveAllPendingImages :exec
UPDATE images SET
    moderation_status = 'approved',
    updated_at = NOW()
WHERE moderation_status = 'pending'
`

func (q *Queries) ApproveAllPendingImages(ctx context.Context) error {
	_, err := q.db.Exec(ctx, approveAllPendingImages)
	return err
}

const countPendingImages = `-- name: CountPendingImages :one
SELECT COUNT(*) FROM images WHERE moderation_status = 'pending'
`

func (q *Queries) CountPendingImages(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingImages)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createImageModeration = `-- name: CreateImageModeration :one
INSERT INTO image_moderations (image_id, status, provider)
VALUES ($1, $2, $3)
RETURNING id, image_id, status, provider, score, labels, reason, moderator_id, created_at, updated_at
`

type CreateImageModerationParams struct {
	ImageID  int64  `json:"image_id"`
	Status   string `json:"status"`
	Provider string `json:"provider"`
}

func (q *Queries) CreateImageModeration(ctx context.Context, arg CreateImageModerationParams) (ImageModeration, error) {
	row := q.db.QueryRow(ctx, createImageModeration, arg.ImageID, arg.Status, arg.Provider)
	var i ImageModeration
	err := row.Scan(
		&i.ID,
		&i.ImageID,
		&i.Status,
		&i.Provider,
		&i.Score,
		&i.Labels,
		&i.Reason,
		&i.ModeratorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getImageModeration = `-- name: GetImageModeration :one
SELECT id, image_id, status, provider, score, labels, reason, moderator_id, created_at, updated_at FROM image_moderations WHERE image_id = $1
`

func (q *Queries) GetImageModeration(ctx context.Context, imageID int64) (ImageModeration, error) {
	row := q.db.QueryRow(ctx, getImageModeration, imageID)
	var i ImageModeration
	err := row.Scan(
		&i.ID,
		&i.ImageID,
		&i.Status,
		&i.Provider,
		&i.Score,
		&i.Labels,
		&i.Reason,
		&i.ModeratorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPendingImages = `-- name: ListPendingImages :many
SELECT i.id, i.user_id, i.album_id, i.group_id, i.strategy_id, i.key, i.path, i.name, i.origin_name, i.size_bytes, i.mimetype, i.extension, i.md5, i.sha1, i.width, i.height, i.permission, i.is_unhealthy, i.uploaded_ip, i.created_at, i.updated_at, i.moderation_status, i.expires_at FROM images i
LEFT JOIN image_moderations m ON i.id = m.image_id
WHERE i.moderation_status = 'pending'
ORDER BY i.created_at DESC
LIMIT $1 OFFSET $2
`

type ListPendingImagesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPendingImages(ctx context.Context, arg ListPendingImagesParams) ([]Image, error) {
	rows, err := q.db.Query(ctx, listPendingImages, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Image{}
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AlbumID,
			&i.GroupID,
			&i.StrategyID,
			&i.Key,
			&i.Path,
			&i.Name,
			&i.OriginName,
			&i.SizeBytes,
			&i.Mimetype,
			&i.Extension,
			&i.Md5,
			&i.Sha1,
			&i.Width,
			&i.Height,
			&i.Permission,
			&i.IsUnhealthy,
			&i.UploadedIp,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ModerationStatus,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateImageModeration = `-- name: UpdateImageModeration :one
UPDATE image_moderations SET
    status = $2,
    moderator_id = $3,
    reason = $4,
    updated_at = NOW()
WHERE image_id = $1
RETURNING id, image_id, status, provider, score, labels, reason, moderator_id, created_at, updated_at
`

type UpdateImageModerationParams struct {
	ImageID     int64       `json:"image_id"`
	Status      string      `json:"status"`
	ModeratorID pgtype.Int8 `json:"moderator_id"`
	Reason      string      `json:"reason"`
}

func (q *Queries) UpdateImageModeration(ctx context.Context, arg UpdateImageModerationParams) (ImageModeration, error) {
	row := q.db.QueryRow(ctx, updateImageModeration,
		arg.ImageID,
		arg.Status,
		arg.ModeratorID,
		arg.Reason,
	)
	var i ImageModeration
	err := row.Scan(
		&i.ID,
		&i.ImageID,
		&i.Status,
		&i.Provider,
		&i.Score,
		&i.Labels,
		&i.Reason,
		&i.ModeratorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateImageModerationStatus = `-- name: UpdateImageModerationStatus :one
UPDATE images SET
    moderation_status = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, album_id, group_id, strategy_id, key, path, name, origin_name, size_bytes, mimetype, extension, md5, sha1, width, height, permission, is_unhealthy, uploaded_ip, created_at, updated_at, moderation_status, expires_at
`

type UpdateImageModerationStatusParams struct {
	ID               int64  `json:"id"`
	ModerationStatus string `json:"moderation_status"`
}

func (q *Queries) UpdateImageModerationStatus(ctx context.Context, arg UpdateImageModerationStatusParams) (Image, error) {
	row := q.db.QueryRow(ctx, updateImageModerationStatus, arg.ID, arg.ModerationStatus)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AlbumID,
		&i.GroupID,
		&i.StrategyID,
		&i.Key,
		&i.Path,
		&i.Name,
		&i.OriginName,
		&i.SizeBytes,
		&i.Mimetype,
		&i.Extension,
		&i.Md5,
		&i.Sha1,
		&i.Width,
		&i.Height,
		&i.Permission,
		&i.IsUnhealthy,
		&i.UploadedIp,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ModerationStatus,
		&i.ExpiresAt,
	)
	return i, err
}
