// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Album struct {
	ID        int64     `json:"id"`
	UserID    int64     `json:"user_id"`
	Name      string    `json:"name"`
	Intro     string    `json:"intro"`
	ImageNum  int64     `json:"image_num"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type ApiToken struct {
	ID         int64              `json:"id"`
	UserID     int64              `json:"user_id"`
	Name       string             `json:"name"`
	TokenHash  string             `json:"token_hash"`
	Scopes     json.RawMessage    `json:"scopes"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  time.Time          `json:"created_at"`
}

type AuditLog struct {
	ID           int64           `json:"id"`
	ActorUserID  pgtype.Int8     `json:"actor_user_id"`
	Action       string          `json:"action"`
	ResourceType string          `json:"resource_type"`
	ResourceID   pgtype.Text     `json:"resource_id"`
	ResourceName pgtype.Text     `json:"resource_name"`
	Details      json.RawMessage `json:"details"`
	Ip           string          `json:"ip"`
	UserAgent    string          `json:"user_agent"`
	CreatedAt    time.Time       `json:"created_at"`
}

type EmailVerificationToken struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt time.Time          `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt time.Time          `json:"created_at"`
}

type Group struct {
	ID        int64           `json:"id"`
	Name      string          `json:"name"`
	IsDefault bool            `json:"is_default"`
	IsGuest   bool            `json:"is_guest"`
	Configs   json.RawMessage `json:"configs"`
	CreatedAt time.Time       `json:"created_at"`
	UpdatedAt time.Time       `json:"updated_at"`
}

type GroupStrategy struct {
	GroupID    int64 `json:"group_id"`
	StrategyID int64 `json:"strategy_id"`
}

type Image struct {
	ID               int64              `json:"id"`
	UserID           pgtype.Int8        `json:"user_id"`
	AlbumID          pgtype.Int8        `json:"album_id"`
	GroupID          pgtype.Int8        `json:"group_id"`
	StrategyID       pgtype.Int8        `json:"strategy_id"`
	Key              string             `json:"key"`
	Path             string             `json:"path"`
	Name             string             `json:"name"`
	OriginName       string             `json:"origin_name"`
	SizeBytes        int64              `json:"size_bytes"`
	Mimetype         string             `json:"mimetype"`
	Extension        string             `json:"extension"`
	Md5              string             `json:"md5"`
	Sha1             string             `json:"sha1"`
	Width            int32              `json:"width"`
	Height           int32              `json:"height"`
	Permission       int16              `json:"permission"`
	IsUnhealthy      bool               `json:"is_unhealthy"`
	UploadedIp       string             `json:"uploaded_ip"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
	ModerationStatus string             `json:"moderation_status"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
}

type ImageModeration struct {
	ID          int64           `json:"id"`
	ImageID     int64           `json:"image_id"`
	Status      string          `json:"status"`
	Provider    string          `json:"provider"`
	Score       pgtype.Numeric  `json:"score"`
	Labels      json.RawMessage `json:"labels"`
	Reason      string          `json:"reason"`
	ModeratorID pgtype.Int8     `json:"moderator_id"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

type RefreshToken struct {
	ID        int64     `json:"id"`
	UserID    int64     `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type SiteSetting struct {
	ID                       int16           `json:"id"`
	AppName                  string          `json:"app_name"`
	AppUrl                   string          `json:"app_url"`
	AllowGuestUpload         bool            `json:"allow_guest_upload"`
	AllowRegistration        bool            `json:"allow_registration"`
	RequireEmailVerification bool            `json:"require_email_verification"`
	UserInitialCapacity      int64           `json:"user_initial_capacity"`
	DefaultImageTtl          string          `json:"default_image_ttl"`
	ModerationMode           string          `json:"moderation_mode"`
	CreatedAt                time.Time       `json:"created_at"`
	UpdatedAt                time.Time       `json:"updated_at"`
	SiteDescription          string          `json:"site_description"`
	FaviconUrl               string          `json:"favicon_url"`
	IcpNumber                string          `json:"icp_number"`
	IcpLink                  string          `json:"icp_link"`
	PsbNumber                string          `json:"psb_number"`
	PsbLink                  string          `json:"psb_link"`
	AnalyticsProvider        string          `json:"analytics_provider"`
	AnalyticsConfig          json.RawMessage `json:"analytics_config"`
}

type Strategy struct {
	ID           int64           `json:"id"`
	Name         string          `json:"name"`
	StrategyType string          `json:"strategy_type"`
	Configs      json.RawMessage `json:"configs"`
	CreatedAt    time.Time       `json:"created_at"`
	UpdatedAt    time.Time       `json:"updated_at"`
}

type User struct {
	ID            int64           `json:"id"`
	GroupID       pgtype.Int8     `json:"group_id"`
	Email         string          `json:"email"`
	Password      string          `json:"password"`
	Name          string          `json:"name"`
	Role          string          `json:"role"`
	CapacityBytes int64           `json:"capacity_bytes"`
	ImageNum      int64           `json:"image_num"`
	AlbumNum      int64           `json:"album_num"`
	Settings      json.RawMessage `json:"settings"`
	Status        int16           `json:"status"`
	EmailVerified bool            `json:"email_verified"`
	RegisteredIp  string          `json:"registered_ip"`
	CreatedAt     time.Time       `json:"created_at"`
	UpdatedAt     time.Time       `json:"updated_at"`
}
