// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox_events.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteOldOutboxEvents = `-- name: DeleteOldOutboxEvents :execrows
DELETE FROM outbox_events
WHERE status IN ('dispatched', 'failed')
  AND created_at < NOW() - make_interval(days => $1)
  AND NOT EXISTS (
      SELECT 1 FROM webhook_deliveries d
      WHERE d.outbox_event_id = outbox_events.id
  )
`

func (q *Queries) DeleteOldOutboxEvents(ctx context.Context, days int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldOutboxEvents, days)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getOutboxEventByID = `-- name: GetOutboxEventByID :one
SELECT id, type, version, idempotency_key, payload, owner_user_id, status, created_at, processed_at FROM outbox_events WHERE id = $1
`

func (q *Queries) GetOutboxEventByID(ctx context.Context, id pgtype.UUID) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, getOutboxEventByID, id)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Version,
		&i.IdempotencyKey,
		&i.Payload,
		&i.OwnerUserID,
		&i.Status,
		&i.CreatedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const getOutboxEventByKey = `-- name: GetOutboxEventByKey :one
SELECT id, type, version, idempotency_key, payload, owner_user_id, status, created_at, processed_at FROM outbox_events WHERE idempotency_key = $1
`

func (q *Queries) GetOutboxEventByKey(ctx context.Context, idempotencyKey string) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, getOutboxEventByKey, idempotencyKey)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Version,
		&i.IdempotencyKey,
		&i.Payload,
		&i.OwnerUserID,
		&i.Status,
		&i.CreatedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const insertOutboxEvent = `-- name: InsertOutboxEvent :one
INSERT INTO outbox_events (type, version, idempotency_key, payload, owner_user_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, type, version, idempotency_key, payload, owner_user_id, status, created_at, processed_at
`

type InsertOutboxEventParams struct {
	Type           string          `json:"type"`
	Version        string          `json:"version"`
	IdempotencyKey string          `json:"idempotency_key"`
	Payload        json.RawMessage `json:"payload"`
	OwnerUserID    pgtype.Int8     `json:"owner_user_id"`
}

func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, insertOutboxEvent,
		arg.Type,
		arg.Version,
		arg.IdempotencyKey,
		arg.Payload,
		arg.OwnerUserID,
	)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Version,
		&i.IdempotencyKey,
		&i.Payload,
		&i.OwnerUserID,
		&i.Status,
		&i.CreatedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const listPendingOutboxEvents = `-- name: ListPendingOutboxEvents :many
SELECT id, type, version, idempotency_key, payload, owner_user_id, status, created_at, processed_at FROM outbox_events
WHERE status = 'pending'
ORDER BY created_at ASC
LIMIT $1
FOR UPDATE SKIP LOCKED
`

func (q *Queries) ListPendingOutboxEvents(ctx context.Context, limit int32) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, listPendingOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OutboxEvent{}
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Version,
			&i.IdempotencyKey,
			&i.Payload,
			&i.OwnerUserID,
			&i.Status,
			&i.CreatedAt,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxEventDispatched = `-- name: MarkOutboxEventDispatched :exec
UPDATE outbox_events
SET status = 'dispatched', processed_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkOutboxEventDispatched(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markOutboxEventDispatched, id)
	return err
}

const markOutboxEventFailed = `-- name: MarkOutboxEventFailed :exec
UPDATE outbox_events
SET status = 'failed', processed_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkOutboxEventFailed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markOutboxEventFailed, id)
	return err
}
