// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: password_reset_tokens.sql

package sqlc

import (
	"context"
	"time"
)

const createPasswordResetToken = `-- name: CreatePasswordResetToken :one
INSERT INTO password_reset_tokens (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, expires_at, used_at, created_at
`

type CreatePasswordResetTokenParams struct {
	UserID    int64     `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, createPasswordResetToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deletePasswordResetTokenByHash = `-- name: DeletePasswordResetTokenByHash :exec
DELETE FROM password_reset_tokens
WHERE token_hash = $1
`

func (q *Queries) DeletePasswordResetTokenByHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deletePasswordResetTokenByHash, tokenHash)
	return err
}

const deleteUnusedPasswordResetTokensByUser = `-- name: DeleteUnusedPasswordResetTokensByUser :exec
DELETE FROM password_reset_tokens
WHERE user_id = $1 AND used_at IS NULL
`

func (q *Queries) DeleteUnusedPasswordResetTokensByUser(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteUnusedPasswordResetTokensByUser, userID)
	return err
}

const getPasswordResetTokenByHash = `-- name: GetPasswordResetTokenByHash :one
SELECT id, user_id, token_hash, expires_at, used_at, created_at FROM password_reset_tokens WHERE token_hash = $1
`

func (q *Queries) GetPasswordResetTokenByHash(ctx context.Context, tokenHash string) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, getPasswordResetTokenByHash, tokenHash)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markPasswordResetTokenUsed = `-- name: MarkPasswordResetTokenUsed :one
UPDATE password_reset_tokens
SET used_at = NOW()
WHERE id = $1 AND used_at IS NULL
RETURNING id, user_id, token_hash, expires_at, used_at, created_at
`

func (q *Queries) MarkPasswordResetTokenUsed(ctx context.Context, id int64) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, markPasswordResetTokenUsed, id)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}
