// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: site_settings.sql

package sqlc

import (
	"context"
	"encoding/json"
)

const getSiteSettings = `-- name: GetSiteSettings :one
SELECT id, app_name, app_url, allow_guest_upload, allow_registration, require_email_verification, user_initial_capacity, default_image_ttl, moderation_mode, created_at, updated_at, site_description, icp_number, icp_link, psb_number, psb_link, analytics_provider, analytics_config FROM site_settings WHERE id = 1
`

func (q *Queries) GetSiteSettings(ctx context.Context) (SiteSetting, error) {
	row := q.db.QueryRow(ctx, getSiteSettings)
	var i SiteSetting
	err := row.Scan(
		&i.ID,
		&i.AppName,
		&i.AppUrl,
		&i.AllowGuestUpload,
		&i.AllowRegistration,
		&i.RequireEmailVerification,
		&i.UserInitialCapacity,
		&i.DefaultImageTtl,
		&i.ModerationMode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SiteDescription,
		&i.IcpNumber,
		&i.IcpLink,
		&i.PsbNumber,
		&i.PsbLink,
		&i.AnalyticsProvider,
		&i.AnalyticsConfig,
	)
	return i, err
}

const upsertSiteSettings = `-- name: UpsertSiteSettings :one
INSERT INTO site_settings (
    id,
    app_name,
    app_url,
    allow_guest_upload,
    allow_registration,
    require_email_verification,
    user_initial_capacity,
    default_image_ttl,
    moderation_mode,
    site_description,
    icp_number,
    icp_link,
    psb_number,
    psb_link,
    analytics_provider,
    analytics_config
)
VALUES (1, $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
ON CONFLICT (id) DO UPDATE SET
    app_name = EXCLUDED.app_name,
    app_url = EXCLUDED.app_url,
    allow_guest_upload = EXCLUDED.allow_guest_upload,
    allow_registration = EXCLUDED.allow_registration,
    require_email_verification = EXCLUDED.require_email_verification,
    user_initial_capacity = EXCLUDED.user_initial_capacity,
    default_image_ttl = EXCLUDED.default_image_ttl,
    moderation_mode = EXCLUDED.moderation_mode,
    site_description = EXCLUDED.site_description,
    icp_number = EXCLUDED.icp_number,
    icp_link = EXCLUDED.icp_link,
    psb_number = EXCLUDED.psb_number,
    psb_link = EXCLUDED.psb_link,
    analytics_provider = EXCLUDED.analytics_provider,
    analytics_config = EXCLUDED.analytics_config,
    updated_at = NOW()
RETURNING id, app_name, app_url, allow_guest_upload, allow_registration, require_email_verification, user_initial_capacity, default_image_ttl, moderation_mode, created_at, updated_at, site_description, icp_number, icp_link, psb_number, psb_link, analytics_provider, analytics_config
`

type UpsertSiteSettingsParams struct {
	AppName                  string          `json:"app_name"`
	AppUrl                   string          `json:"app_url"`
	AllowGuestUpload         bool            `json:"allow_guest_upload"`
	AllowRegistration        bool            `json:"allow_registration"`
	RequireEmailVerification bool            `json:"require_email_verification"`
	UserInitialCapacity      int64           `json:"user_initial_capacity"`
	DefaultImageTtl          string          `json:"default_image_ttl"`
	ModerationMode           string          `json:"moderation_mode"`
	SiteDescription          string          `json:"site_description"`
	IcpNumber                string          `json:"icp_number"`
	IcpLink                  string          `json:"icp_link"`
	PsbNumber                string          `json:"psb_number"`
	PsbLink                  string          `json:"psb_link"`
	AnalyticsProvider        string          `json:"analytics_provider"`
	AnalyticsConfig          json.RawMessage `json:"analytics_config"`
}

func (q *Queries) UpsertSiteSettings(ctx context.Context, arg UpsertSiteSettingsParams) (SiteSetting, error) {
	row := q.db.QueryRow(ctx, upsertSiteSettings,
		arg.AppName,
		arg.AppUrl,
		arg.AllowGuestUpload,
		arg.AllowRegistration,
		arg.RequireEmailVerification,
		arg.UserInitialCapacity,
		arg.DefaultImageTtl,
		arg.ModerationMode,
		arg.SiteDescription,
		arg.IcpNumber,
		arg.IcpLink,
		arg.PsbNumber,
		arg.PsbLink,
		arg.AnalyticsProvider,
		arg.AnalyticsConfig,
	)
	var i SiteSetting
	err := row.Scan(
		&i.ID,
		&i.AppName,
		&i.AppUrl,
		&i.AllowGuestUpload,
		&i.AllowRegistration,
		&i.RequireEmailVerification,
		&i.UserInitialCapacity,
		&i.DefaultImageTtl,
		&i.ModerationMode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SiteDescription,
		&i.IcpNumber,
		&i.IcpLink,
		&i.PsbNumber,
		&i.PsbLink,
		&i.AnalyticsProvider,
		&i.AnalyticsConfig,
	)
	return i, err
}
