// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: site_settings.sql

package sqlc

import (
	"context"
	"encoding/json"
)

const getSiteSettings = `-- name: GetSiteSettings :one
SELECT id, app_name, app_url, allow_guest_upload, allow_registration, require_email_verification, user_initial_capacity, default_image_ttl, moderation_mode, created_at, updated_at, site_description, analytics_provider, analytics_config, favicon_url, guest_capacity_bytes, allow_user_image_processing, footer_text_1, footer_link_1, footer_text_2, footer_link_2, guest_image_ttl, theme_config, allow_oauth_registration, skip_image_processing FROM site_settings WHERE id = 1
`

func (q *Queries) GetSiteSettings(ctx context.Context) (SiteSetting, error) {
	row := q.db.QueryRow(ctx, getSiteSettings)
	var i SiteSetting
	err := row.Scan(
		&i.ID,
		&i.AppName,
		&i.AppUrl,
		&i.AllowGuestUpload,
		&i.AllowRegistration,
		&i.RequireEmailVerification,
		&i.UserInitialCapacity,
		&i.DefaultImageTtl,
		&i.ModerationMode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SiteDescription,
		&i.AnalyticsProvider,
		&i.AnalyticsConfig,
		&i.FaviconUrl,
		&i.GuestCapacityBytes,
		&i.AllowUserImageProcessing,
		&i.FooterText1,
		&i.FooterLink1,
		&i.FooterText2,
		&i.FooterLink2,
		&i.GuestImageTtl,
		&i.ThemeConfig,
		&i.AllowOauthRegistration,
		&i.SkipImageProcessing,
	)
	return i, err
}

const upsertSiteSettings = `-- name: UpsertSiteSettings :one
INSERT INTO site_settings (
    id,
    app_name,
    app_url,
    allow_guest_upload,
    guest_capacity_bytes,
    allow_registration,
    allow_oauth_registration,
    require_email_verification,
    user_initial_capacity,
    default_image_ttl,
    guest_image_ttl,
    moderation_mode,
    site_description,
    favicon_url,
    footer_text_1,
    footer_link_1,
    footer_text_2,
    footer_link_2,
    analytics_provider,
    analytics_config,
    allow_user_image_processing,
    skip_image_processing,
    theme_config
)
VALUES (1, $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22)
ON CONFLICT (id) DO UPDATE SET
    app_name = EXCLUDED.app_name,
    app_url = EXCLUDED.app_url,
    allow_guest_upload = EXCLUDED.allow_guest_upload,
    guest_capacity_bytes = EXCLUDED.guest_capacity_bytes,
    allow_registration = EXCLUDED.allow_registration,
    allow_oauth_registration = EXCLUDED.allow_oauth_registration,
    require_email_verification = EXCLUDED.require_email_verification,
    user_initial_capacity = EXCLUDED.user_initial_capacity,
    default_image_ttl = EXCLUDED.default_image_ttl,
    guest_image_ttl = EXCLUDED.guest_image_ttl,
    moderation_mode = EXCLUDED.moderation_mode,
    site_description = EXCLUDED.site_description,
    favicon_url = EXCLUDED.favicon_url,
    footer_text_1 = EXCLUDED.footer_text_1,
    footer_link_1 = EXCLUDED.footer_link_1,
    footer_text_2 = EXCLUDED.footer_text_2,
    footer_link_2 = EXCLUDED.footer_link_2,
    analytics_provider = EXCLUDED.analytics_provider,
    analytics_config = EXCLUDED.analytics_config,
    allow_user_image_processing = EXCLUDED.allow_user_image_processing,
    skip_image_processing = EXCLUDED.skip_image_processing,
    theme_config = EXCLUDED.theme_config,
    updated_at = NOW()
RETURNING id, app_name, app_url, allow_guest_upload, allow_registration, require_email_verification, user_initial_capacity, default_image_ttl, moderation_mode, created_at, updated_at, site_description, analytics_provider, analytics_config, favicon_url, guest_capacity_bytes, allow_user_image_processing, footer_text_1, footer_link_1, footer_text_2, footer_link_2, guest_image_ttl, theme_config, allow_oauth_registration, skip_image_processing
`

type UpsertSiteSettingsParams struct {
	AppName                  string          `json:"app_name"`
	AppUrl                   string          `json:"app_url"`
	AllowGuestUpload         bool            `json:"allow_guest_upload"`
	GuestCapacityBytes       int64           `json:"guest_capacity_bytes"`
	AllowRegistration        bool            `json:"allow_registration"`
	AllowOauthRegistration   bool            `json:"allow_oauth_registration"`
	RequireEmailVerification bool            `json:"require_email_verification"`
	UserInitialCapacity      int64           `json:"user_initial_capacity"`
	DefaultImageTtl          string          `json:"default_image_ttl"`
	GuestImageTtl            string          `json:"guest_image_ttl"`
	ModerationMode           string          `json:"moderation_mode"`
	SiteDescription          string          `json:"site_description"`
	FaviconUrl               string          `json:"favicon_url"`
	FooterText1              string          `json:"footer_text_1"`
	FooterLink1              string          `json:"footer_link_1"`
	FooterText2              string          `json:"footer_text_2"`
	FooterLink2              string          `json:"footer_link_2"`
	AnalyticsProvider        string          `json:"analytics_provider"`
	AnalyticsConfig          json.RawMessage `json:"analytics_config"`
	AllowUserImageProcessing bool            `json:"allow_user_image_processing"`
	SkipImageProcessing      bool            `json:"skip_image_processing"`
	ThemeConfig              json.RawMessage `json:"theme_config"`
}

func (q *Queries) UpsertSiteSettings(ctx context.Context, arg UpsertSiteSettingsParams) (SiteSetting, error) {
	row := q.db.QueryRow(ctx, upsertSiteSettings,
		arg.AppName,
		arg.AppUrl,
		arg.AllowGuestUpload,
		arg.GuestCapacityBytes,
		arg.AllowRegistration,
		arg.AllowOauthRegistration,
		arg.RequireEmailVerification,
		arg.UserInitialCapacity,
		arg.DefaultImageTtl,
		arg.GuestImageTtl,
		arg.ModerationMode,
		arg.SiteDescription,
		arg.FaviconUrl,
		arg.FooterText1,
		arg.FooterLink1,
		arg.FooterText2,
		arg.FooterLink2,
		arg.AnalyticsProvider,
		arg.AnalyticsConfig,
		arg.AllowUserImageProcessing,
		arg.SkipImageProcessing,
		arg.ThemeConfig,
	)
	var i SiteSetting
	err := row.Scan(
		&i.ID,
		&i.AppName,
		&i.AppUrl,
		&i.AllowGuestUpload,
		&i.AllowRegistration,
		&i.RequireEmailVerification,
		&i.UserInitialCapacity,
		&i.DefaultImageTtl,
		&i.ModerationMode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SiteDescription,
		&i.AnalyticsProvider,
		&i.AnalyticsConfig,
		&i.FaviconUrl,
		&i.GuestCapacityBytes,
		&i.AllowUserImageProcessing,
		&i.FooterText1,
		&i.FooterLink1,
		&i.FooterText2,
		&i.FooterLink2,
		&i.GuestImageTtl,
		&i.ThemeConfig,
		&i.AllowOauthRegistration,
		&i.SkipImageProcessing,
	)
	return i, err
}
