// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: strategies.sql

package sqlc

import (
	"context"
	"encoding/json"
)

const createStrategy = `-- name: CreateStrategy :one
INSERT INTO strategies (name, strategy_type, configs)
VALUES ($1, $2, $3)
RETURNING id, name, strategy_type, configs, created_at, updated_at
`

type CreateStrategyParams struct {
	Name         string          `json:"name"`
	StrategyType string          `json:"strategy_type"`
	Configs      json.RawMessage `json:"configs"`
}

func (q *Queries) CreateStrategy(ctx context.Context, arg CreateStrategyParams) (Strategy, error) {
	row := q.db.QueryRow(ctx, createStrategy, arg.Name, arg.StrategyType, arg.Configs)
	var i Strategy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StrategyType,
		&i.Configs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteStrategy = `-- name: DeleteStrategy :exec
DELETE FROM strategies WHERE id = $1
`

func (q *Queries) DeleteStrategy(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteStrategy, id)
	return err
}

const getStrategyByID = `-- name: GetStrategyByID :one
SELECT id, name, strategy_type, configs, created_at, updated_at FROM strategies WHERE id = $1
`

func (q *Queries) GetStrategyByID(ctx context.Context, id int64) (Strategy, error) {
	row := q.db.QueryRow(ctx, getStrategyByID, id)
	var i Strategy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StrategyType,
		&i.Configs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStrategies = `-- name: ListStrategies :many
SELECT id, name, strategy_type, configs, created_at, updated_at FROM strategies ORDER BY created_at DESC
`

func (q *Queries) ListStrategies(ctx context.Context) ([]Strategy, error) {
	rows, err := q.db.Query(ctx, listStrategies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Strategy{}
	for rows.Next() {
		var i Strategy
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.StrategyType,
			&i.Configs,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStrategy = `-- name: UpdateStrategy :one
UPDATE strategies SET
    name = $2,
    strategy_type = $3,
    configs = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, strategy_type, configs, created_at, updated_at
`

type UpdateStrategyParams struct {
	ID           int64           `json:"id"`
	Name         string          `json:"name"`
	StrategyType string          `json:"strategy_type"`
	Configs      json.RawMessage `json:"configs"`
}

func (q *Queries) UpdateStrategy(ctx context.Context, arg UpdateStrategyParams) (Strategy, error) {
	row := q.db.QueryRow(ctx, updateStrategy,
		arg.ID,
		arg.Name,
		arg.StrategyType,
		arg.Configs,
	)
	var i Strategy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StrategyType,
		&i.Configs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
