// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tags.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addImageTag = `-- name: AddImageTag :exec
INSERT INTO image_tags (image_id, tag_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddImageTagParams struct {
	ImageID int64 `json:"image_id"`
	TagID   int64 `json:"tag_id"`
}

func (q *Queries) AddImageTag(ctx context.Context, arg AddImageTagParams) error {
	_, err := q.db.Exec(ctx, addImageTag, arg.ImageID, arg.TagID)
	return err
}

const createTag = `-- name: CreateTag :one
INSERT INTO tags (user_id, name, type)
VALUES ($1, $2, $3)
RETURNING id, user_id, name, type, created_at, updated_at
`

type CreateTagParams struct {
	UserID pgtype.Int8 `json:"user_id"`
	Name   string      `json:"name"`
	Type   string      `json:"type"`
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, createTag, arg.UserID, arg.Name, arg.Type)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getImageTags = `-- name: GetImageTags :many
SELECT t.id, t.user_id, t.name, t.type, t.created_at, t.updated_at
FROM tags t
JOIN image_tags it ON t.id = it.tag_id
WHERE it.image_id = $1
ORDER BY t.name ASC
`

func (q *Queries) GetImageTags(ctx context.Context, imageID int64) ([]Tag, error) {
	rows, err := q.db.Query(ctx, getImageTags, imageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTagByID = `-- name: GetTagByID :one
SELECT id, user_id, name, type, created_at, updated_at FROM tags WHERE id = $1
`

func (q *Queries) GetTagByID(ctx context.Context, id int64) (Tag, error) {
	row := q.db.QueryRow(ctx, getTagByID, id)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTagsByUserID = `-- name: GetTagsByUserID :many
SELECT id, user_id, name, type, created_at, updated_at FROM tags
WHERE user_id = $1
ORDER BY name ASC
`

func (q *Queries) GetTagsByUserID(ctx context.Context, userID pgtype.Int8) ([]Tag, error) {
	rows, err := q.db.Query(ctx, getTagsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeImageTag = `-- name: RemoveImageTag :exec
DELETE FROM image_tags
WHERE image_id = $1 AND tag_id = $2
`

type RemoveImageTagParams struct {
	ImageID int64 `json:"image_id"`
	TagID   int64 `json:"tag_id"`
}

func (q *Queries) RemoveImageTag(ctx context.Context, arg RemoveImageTagParams) error {
	_, err := q.db.Exec(ctx, removeImageTag, arg.ImageID, arg.TagID)
	return err
}
