// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdminUser = `-- name: CreateAdminUser :one
INSERT INTO users (group_id, email, password, name, role, capacity_bytes, settings, status, email_verified, registered_ip)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, '')
RETURNING id, group_id, email, password, name, role, capacity_bytes, image_num, album_num, settings, status, email_verified, registered_ip, created_at, updated_at
`

type CreateAdminUserParams struct {
	GroupID       pgtype.Int8     `json:"group_id"`
	Email         string          `json:"email"`
	Password      string          `json:"password"`
	Name          string          `json:"name"`
	Role          string          `json:"role"`
	CapacityBytes int64           `json:"capacity_bytes"`
	Settings      json.RawMessage `json:"settings"`
	Status        int16           `json:"status"`
	EmailVerified bool            `json:"email_verified"`
}

func (q *Queries) CreateAdminUser(ctx context.Context, arg CreateAdminUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createAdminUser,
		arg.GroupID,
		arg.Email,
		arg.Password,
		arg.Name,
		arg.Role,
		arg.CapacityBytes,
		arg.Settings,
		arg.Status,
		arg.EmailVerified,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Email,
		&i.Password,
		&i.Name,
		&i.Role,
		&i.CapacityBytes,
		&i.ImageNum,
		&i.AlbumNum,
		&i.Settings,
		&i.Status,
		&i.EmailVerified,
		&i.RegisteredIp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (group_id, email, password, name, role, capacity_bytes, settings, status, email_verified, registered_ip)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, group_id, email, password, name, role, capacity_bytes, image_num, album_num, settings, status, email_verified, registered_ip, created_at, updated_at
`

type CreateUserParams struct {
	GroupID       pgtype.Int8     `json:"group_id"`
	Email         string          `json:"email"`
	Password      string          `json:"password"`
	Name          string          `json:"name"`
	Role          string          `json:"role"`
	CapacityBytes int64           `json:"capacity_bytes"`
	Settings      json.RawMessage `json:"settings"`
	Status        int16           `json:"status"`
	EmailVerified bool            `json:"email_verified"`
	RegisteredIp  string          `json:"registered_ip"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.GroupID,
		arg.Email,
		arg.Password,
		arg.Name,
		arg.Role,
		arg.CapacityBytes,
		arg.Settings,
		arg.Status,
		arg.EmailVerified,
		arg.RegisteredIp,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Email,
		&i.Password,
		&i.Name,
		&i.Role,
		&i.CapacityBytes,
		&i.ImageNum,
		&i.AlbumNum,
		&i.Settings,
		&i.Status,
		&i.EmailVerified,
		&i.RegisteredIp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const decrementUserImageNum = `-- name: DecrementUserImageNum :exec
UPDATE users SET image_num = image_num - 1, updated_at = NOW() WHERE id = $1 AND image_num > 0
`

func (q *Queries) DecrementUserImageNum(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, decrementUserImageNum, id)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, group_id, email, password, name, role, capacity_bytes, image_num, album_num, settings, status, email_verified, registered_ip, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Email,
		&i.Password,
		&i.Name,
		&i.Role,
		&i.CapacityBytes,
		&i.ImageNum,
		&i.AlbumNum,
		&i.Settings,
		&i.Status,
		&i.EmailVerified,
		&i.RegisteredIp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, group_id, email, password, name, role, capacity_bytes, image_num, album_num, settings, status, email_verified, registered_ip, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Email,
		&i.Password,
		&i.Name,
		&i.Role,
		&i.CapacityBytes,
		&i.ImageNum,
		&i.AlbumNum,
		&i.Settings,
		&i.Status,
		&i.EmailVerified,
		&i.RegisteredIp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserUsedCapacity = `-- name: GetUserUsedCapacity :one
SELECT COALESCE(SUM(size_bytes), 0) FROM images WHERE user_id = $1
`

func (q *Queries) GetUserUsedCapacity(ctx context.Context, userID pgtype.Int8) (interface{}, error) {
	row := q.db.QueryRow(ctx, getUserUsedCapacity, userID)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const incrementUserImageNum = `-- name: IncrementUserImageNum :exec
UPDATE users SET image_num = image_num + 1, updated_at = NOW() WHERE id = $1
`

func (q *Queries) IncrementUserImageNum(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, incrementUserImageNum, id)
	return err
}

const listAllUsers = `-- name: ListAllUsers :many
SELECT id, group_id, email, password, name, role, capacity_bytes, image_num, album_num, settings, status, email_verified, registered_ip, created_at, updated_at FROM users ORDER BY created_at DESC
`

func (q *Queries) ListAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Email,
			&i.Password,
			&i.Name,
			&i.Role,
			&i.CapacityBytes,
			&i.ImageNum,
			&i.AlbumNum,
			&i.Settings,
			&i.Status,
			&i.EmailVerified,
			&i.RegisteredIp,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, group_id, email, password, name, role, capacity_bytes, image_num, album_num, settings, status, email_verified, registered_ip, created_at, updated_at FROM users
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Email,
			&i.Password,
			&i.Name,
			&i.Role,
			&i.CapacityBytes,
			&i.ImageNum,
			&i.AlbumNum,
			&i.Settings,
			&i.Status,
			&i.EmailVerified,
			&i.RegisteredIp,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET
    name = $2,
    password = $3,
    group_id = $4,
    capacity_bytes = $5,
    status = $6,
    settings = $7,
    updated_at = NOW()
WHERE id = $1
RETURNING id, group_id, email, password, name, role, capacity_bytes, image_num, album_num, settings, status, email_verified, registered_ip, created_at, updated_at
`

type UpdateUserParams struct {
	ID            int64           `json:"id"`
	Name          string          `json:"name"`
	Password      string          `json:"password"`
	GroupID       pgtype.Int8     `json:"group_id"`
	CapacityBytes int64           `json:"capacity_bytes"`
	Status        int16           `json:"status"`
	Settings      json.RawMessage `json:"settings"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Name,
		arg.Password,
		arg.GroupID,
		arg.CapacityBytes,
		arg.Status,
		arg.Settings,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Email,
		&i.Password,
		&i.Name,
		&i.Role,
		&i.CapacityBytes,
		&i.ImageNum,
		&i.AlbumNum,
		&i.Settings,
		&i.Status,
		&i.EmailVerified,
		&i.RegisteredIp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
