// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_identities.sql

package sqlc

import (
	"context"
)

const createUserIdentity = `-- name: CreateUserIdentity :one
INSERT INTO user_identities (user_id, provider, provider_subject, email)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, provider, provider_subject, email, linked_at
`

type CreateUserIdentityParams struct {
	UserID          int64  `json:"user_id"`
	Provider        string `json:"provider"`
	ProviderSubject string `json:"provider_subject"`
	Email           string `json:"email"`
}

func (q *Queries) CreateUserIdentity(ctx context.Context, arg CreateUserIdentityParams) (UserIdentity, error) {
	row := q.db.QueryRow(ctx, createUserIdentity,
		arg.UserID,
		arg.Provider,
		arg.ProviderSubject,
		arg.Email,
	)
	var i UserIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderSubject,
		&i.Email,
		&i.LinkedAt,
	)
	return i, err
}

const deleteUserIdentity = `-- name: DeleteUserIdentity :exec
DELETE FROM user_identities
WHERE user_id = $1 AND provider = $2
`

type DeleteUserIdentityParams struct {
	UserID   int64  `json:"user_id"`
	Provider string `json:"provider"`
}

func (q *Queries) DeleteUserIdentity(ctx context.Context, arg DeleteUserIdentityParams) error {
	_, err := q.db.Exec(ctx, deleteUserIdentity, arg.UserID, arg.Provider)
	return err
}

const getUserIdentityByProviderSubject = `-- name: GetUserIdentityByProviderSubject :one
SELECT id, user_id, provider, provider_subject, email, linked_at FROM user_identities
WHERE provider = $1 AND provider_subject = $2
`

type GetUserIdentityByProviderSubjectParams struct {
	Provider        string `json:"provider"`
	ProviderSubject string `json:"provider_subject"`
}

func (q *Queries) GetUserIdentityByProviderSubject(ctx context.Context, arg GetUserIdentityByProviderSubjectParams) (UserIdentity, error) {
	row := q.db.QueryRow(ctx, getUserIdentityByProviderSubject, arg.Provider, arg.ProviderSubject)
	var i UserIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderSubject,
		&i.Email,
		&i.LinkedAt,
	)
	return i, err
}

const listUserIdentitiesByUser = `-- name: ListUserIdentitiesByUser :many
SELECT id, user_id, provider, provider_subject, email, linked_at FROM user_identities
WHERE user_id = $1
ORDER BY linked_at DESC
`

func (q *Queries) ListUserIdentitiesByUser(ctx context.Context, userID int64) ([]UserIdentity, error) {
	rows, err := q.db.Query(ctx, listUserIdentitiesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserIdentity{}
	for rows.Next() {
		var i UserIdentity
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.ProviderSubject,
			&i.Email,
			&i.LinkedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
