// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhooks.sql

package sqlc

import (
	"context"
	"encoding/json"
)

const countWebhooksByUser = `-- name: CountWebhooksByUser :one
SELECT COUNT(*) FROM webhooks WHERE user_id = $1
`

func (q *Queries) CountWebhooksByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countWebhooksByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWebhook = `-- name: CreateWebhook :one
INSERT INTO webhooks (user_id, name, url, secret_hash, secret_ciphertext, events)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, name, url, secret_hash, events, enabled, created_at, updated_at, secret_ciphertext
`

type CreateWebhookParams struct {
	UserID           int64           `json:"user_id"`
	Name             string          `json:"name"`
	Url              string          `json:"url"`
	SecretHash       string          `json:"secret_hash"`
	SecretCiphertext []byte          `json:"secret_ciphertext"`
	Events           json.RawMessage `json:"events"`
}

func (q *Queries) CreateWebhook(ctx context.Context, arg CreateWebhookParams) (Webhook, error) {
	row := q.db.QueryRow(ctx, createWebhook,
		arg.UserID,
		arg.Name,
		arg.Url,
		arg.SecretHash,
		arg.SecretCiphertext,
		arg.Events,
	)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Url,
		&i.SecretHash,
		&i.Events,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SecretCiphertext,
	)
	return i, err
}

const deleteWebhook = `-- name: DeleteWebhook :exec
DELETE FROM webhooks WHERE id = $1 AND user_id = $2
`

type DeleteWebhookParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteWebhook(ctx context.Context, arg DeleteWebhookParams) error {
	_, err := q.db.Exec(ctx, deleteWebhook, arg.ID, arg.UserID)
	return err
}

const getWebhookByID = `-- name: GetWebhookByID :one
SELECT id, user_id, name, url, secret_hash, events, enabled, created_at, updated_at, secret_ciphertext FROM webhooks WHERE id = $1
`

func (q *Queries) GetWebhookByID(ctx context.Context, id int64) (Webhook, error) {
	row := q.db.QueryRow(ctx, getWebhookByID, id)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Url,
		&i.SecretHash,
		&i.Events,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SecretCiphertext,
	)
	return i, err
}

const listEnabledWebhooks = `-- name: ListEnabledWebhooks :many
SELECT id, user_id, name, url, secret_hash, events, enabled, created_at, updated_at, secret_ciphertext FROM webhooks
WHERE enabled = TRUE
ORDER BY id
`

func (q *Queries) ListEnabledWebhooks(ctx context.Context) ([]Webhook, error) {
	rows, err := q.db.Query(ctx, listEnabledWebhooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Webhook{}
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Url,
			&i.SecretHash,
			&i.Events,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SecretCiphertext,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhooksByUser = `-- name: ListWebhooksByUser :many
SELECT id, user_id, name, url, secret_hash, events, enabled, created_at, updated_at, secret_ciphertext FROM webhooks
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListWebhooksByUser(ctx context.Context, userID int64) ([]Webhook, error) {
	rows, err := q.db.Query(ctx, listWebhooksByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Webhook{}
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Url,
			&i.SecretHash,
			&i.Events,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SecretCiphertext,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWebhook = `-- name: UpdateWebhook :one
UPDATE webhooks SET
    name = COALESCE($2, name),
    url = COALESCE($3, url),
    events = COALESCE($4, events),
    enabled = COALESCE($5, enabled),
    updated_at = NOW()
WHERE id = $1 AND user_id = $6
RETURNING id, user_id, name, url, secret_hash, events, enabled, created_at, updated_at, secret_ciphertext
`

type UpdateWebhookParams struct {
	ID      int64           `json:"id"`
	Name    string          `json:"name"`
	Url     string          `json:"url"`
	Events  json.RawMessage `json:"events"`
	Enabled bool            `json:"enabled"`
	UserID  int64           `json:"user_id"`
}

func (q *Queries) UpdateWebhook(ctx context.Context, arg UpdateWebhookParams) (Webhook, error) {
	row := q.db.QueryRow(ctx, updateWebhook,
		arg.ID,
		arg.Name,
		arg.Url,
		arg.Events,
		arg.Enabled,
		arg.UserID,
	)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Url,
		&i.SecretHash,
		&i.Events,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SecretCiphertext,
	)
	return i, err
}

const updateWebhookSecret = `-- name: UpdateWebhookSecret :exec
UPDATE webhooks SET
    secret_hash = $2,
    secret_ciphertext = $3,
    updated_at = NOW()
WHERE id = $1
`

type UpdateWebhookSecretParams struct {
	ID               int64  `json:"id"`
	SecretHash       string `json:"secret_hash"`
	SecretCiphertext []byte `json:"secret_ciphertext"`
}

func (q *Queries) UpdateWebhookSecret(ctx context.Context, arg UpdateWebhookSecretParams) error {
	_, err := q.db.Exec(ctx, updateWebhookSecret, arg.ID, arg.SecretHash, arg.SecretCiphertext)
	return err
}
