// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhook_deliveries.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countWebhookDeliveriesByWebhook = `-- name: CountWebhookDeliveriesByWebhook :one
SELECT COUNT(*) FROM webhook_deliveries WHERE webhook_id = $1
`

func (q *Queries) CountWebhookDeliveriesByWebhook(ctx context.Context, webhookID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countWebhookDeliveriesByWebhook, webhookID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWebhookDelivery = `-- name: CreateWebhookDelivery :one
INSERT INTO webhook_deliveries (webhook_id, outbox_event_id, request_headers)
VALUES ($1, $2, $3)
RETURNING id, webhook_id, outbox_event_id, status, attempt, max_attempts, next_retry_at, request_headers, response_status, response_body, error_message, duration_ms, created_at, completed_at
`

type CreateWebhookDeliveryParams struct {
	WebhookID      int64           `json:"webhook_id"`
	OutboxEventID  pgtype.UUID     `json:"outbox_event_id"`
	RequestHeaders json.RawMessage `json:"request_headers"`
}

func (q *Queries) CreateWebhookDelivery(ctx context.Context, arg CreateWebhookDeliveryParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, createWebhookDelivery, arg.WebhookID, arg.OutboxEventID, arg.RequestHeaders)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.WebhookID,
		&i.OutboxEventID,
		&i.Status,
		&i.Attempt,
		&i.MaxAttempts,
		&i.NextRetryAt,
		&i.RequestHeaders,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.ErrorMessage,
		&i.DurationMs,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const deleteOldWebhookDeliveries = `-- name: DeleteOldWebhookDeliveries :execrows
DELETE FROM webhook_deliveries
WHERE status IN ('delivered', 'dead')
  AND created_at < NOW() - make_interval(days => $1)
`

func (q *Queries) DeleteOldWebhookDeliveries(ctx context.Context, days int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldWebhookDeliveries, days)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getWebhookDeliveryByID = `-- name: GetWebhookDeliveryByID :one
SELECT id, webhook_id, outbox_event_id, status, attempt, max_attempts, next_retry_at, request_headers, response_status, response_body, error_message, duration_ms, created_at, completed_at FROM webhook_deliveries WHERE id = $1
`

func (q *Queries) GetWebhookDeliveryByID(ctx context.Context, id int64) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, getWebhookDeliveryByID, id)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.WebhookID,
		&i.OutboxEventID,
		&i.Status,
		&i.Attempt,
		&i.MaxAttempts,
		&i.NextRetryAt,
		&i.RequestHeaders,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.ErrorMessage,
		&i.DurationMs,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listPendingWebhookDeliveries = `-- name: ListPendingWebhookDeliveries :many
SELECT id, webhook_id, outbox_event_id, status, attempt, max_attempts, next_retry_at, request_headers, response_status, response_body, error_message, duration_ms, created_at, completed_at FROM webhook_deliveries
WHERE status IN ('pending', 'retrying')
  AND next_retry_at <= NOW()
ORDER BY next_retry_at ASC
LIMIT $1
FOR UPDATE SKIP LOCKED
`

func (q *Queries) ListPendingWebhookDeliveries(ctx context.Context, limit int32) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, listPendingWebhookDeliveries, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookDelivery{}
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.WebhookID,
			&i.OutboxEventID,
			&i.Status,
			&i.Attempt,
			&i.MaxAttempts,
			&i.NextRetryAt,
			&i.RequestHeaders,
			&i.ResponseStatus,
			&i.ResponseBody,
			&i.ErrorMessage,
			&i.DurationMs,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookDeliveriesByWebhook = `-- name: ListWebhookDeliveriesByWebhook :many
SELECT id, webhook_id, outbox_event_id, status, attempt, max_attempts, next_retry_at, request_headers, response_status, response_body, error_message, duration_ms, created_at, completed_at FROM webhook_deliveries
WHERE webhook_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListWebhookDeliveriesByWebhookParams struct {
	WebhookID int64 `json:"webhook_id"`
	Limit     int32 `json:"limit"`
	Offset    int32 `json:"offset"`
}

func (q *Queries) ListWebhookDeliveriesByWebhook(ctx context.Context, arg ListWebhookDeliveriesByWebhookParams) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, listWebhookDeliveriesByWebhook, arg.WebhookID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookDelivery{}
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.WebhookID,
			&i.OutboxEventID,
			&i.Status,
			&i.Attempt,
			&i.MaxAttempts,
			&i.NextRetryAt,
			&i.RequestHeaders,
			&i.ResponseStatus,
			&i.ResponseBody,
			&i.ErrorMessage,
			&i.DurationMs,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetWebhookDeliveryForReplay = `-- name: ResetWebhookDeliveryForReplay :exec
UPDATE webhook_deliveries SET
    status = 'pending',
    attempt = 0,
    next_retry_at = NOW(),
    error_message = '',
    completed_at = NULL
WHERE id = $1
`

func (q *Queries) ResetWebhookDeliveryForReplay(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, resetWebhookDeliveryForReplay, id)
	return err
}

const updateWebhookDeliveryStatus = `-- name: UpdateWebhookDeliveryStatus :exec
UPDATE webhook_deliveries SET
    status = $2,
    attempt = $3,
    next_retry_at = $4,
    response_status = $5,
    response_body = $6,
    error_message = $7,
    duration_ms = $8,
    completed_at = CASE WHEN $9::boolean THEN NOW() ELSE completed_at END
WHERE id = $1
`

type UpdateWebhookDeliveryStatusParams struct {
	ID             int64       `json:"id"`
	Status         string      `json:"status"`
	Attempt        int32       `json:"attempt"`
	NextRetryAt    time.Time   `json:"next_retry_at"`
	ResponseStatus pgtype.Int4 `json:"response_status"`
	ResponseBody   string      `json:"response_body"`
	ErrorMessage   string      `json:"error_message"`
	DurationMs     pgtype.Int4 `json:"duration_ms"`
	Column9        bool        `json:"column_9"`
}

func (q *Queries) UpdateWebhookDeliveryStatus(ctx context.Context, arg UpdateWebhookDeliveryStatusParams) error {
	_, err := q.db.Exec(ctx, updateWebhookDeliveryStatus,
		arg.ID,
		arg.Status,
		arg.Attempt,
		arg.NextRetryAt,
		arg.ResponseStatus,
		arg.ResponseBody,
		arg.ErrorMessage,
		arg.DurationMs,
		arg.Column9,
	)
	return err
}
